### PR TITLE
[773] Remove rails-erd gem

### PR DESCRIPTION
**Pull request by jhenderson**
### Context
After upgrading to Rails to 6.1 we got the following error from the rails-erd gem after running `rake db:migrate`:

```ruby
rake aborted!
NoMethodError: undefined method `parent' for RegisterTraineeTeachers::Application:Class
Did you mean?  present?
```

The team has also agreed that it's not needed at the moment and should only be reintroduced if there's a good case for it and it supports the latest version of rails.

https://trello.com/c/rg3lvFxw/773-remove-rails-erd-gem

### CODE REVIEW

**Review by defong — APPROVED** [review]
Do we need to drop the jpg as well?

**Comment by defong** [comment]
[Remove rails-erd gem](https://trello.com/c/rg3lvFxw/773-remove-rails-erd-gem)
